### ISSUE TITLE
Application behaves strangely when there is a single quote characters in the conversation's title

### ISSUE THREAD

**Issue by jonatasoliveira** [victor-torres/whatsapp-applescript#4]
I tried to send a message to `"Aninha D'Aguiar"` but the message was sent to the last person that I had sent before Aninha.

It worked when I escaped the quote like this: `"Aninha D\'Aguiar"`

**Comment by victor-torres** [comment]
```
set conversation_title to quoted form of first item of arguments
set message to quoted form of second item of arguments
```

**Comment by victor-torres** [comment]
Sorry, tests weren't correct and the issue persists.

**Comment by victor-torres** [comment]
Using `"`s  instead of `'`s
