### ISSUE TITLE
Chat selection is not working

### ISSUE THREAD

**Issue by victor-torres** [victor-torres/whatsapp-applescript#6]
Somehow chat/conversation selection stopped working. Need to debug and see what's happening.

**Comment by victor-torres** [comment]
element.click() do not work anymore :(
seems like whatsapp react only listen to its special virtual mouse events
I took a look at http://jsfiddle.net/hulufei/twr4thuh/7/ and maybe it will work.
Is sad to know we have to inject another code in addition to jQuery which we're already putting inside whatsapp instance... But it's not our fault react won't offer a public API for us to use.

resources:
- https://facebook.github.io/react/docs/test-utils.html

**Comment by sunnypp** [comment]
Thanks for the script! Please check if #8 fixes this! 😉

**Comment by victor-torres** [comment]
Thanks. Yes it fixes, @sunnypp :)
